import Link from "next/link";
import Image from "next/image";
import { cookies } from "next/headers";
import { SESSION_COOKIE, verifySessionToken } from "@/core/auth/session";
import {
  Wand2,
  ScanSearch,
  Lightbulb,
  ImageIcon,
  LayoutTemplate,
  Download,
  Upload,
  Sparkles,
  ArrowRight,
  Gem,
  Dna,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { type ExampleCard } from "@/components/landing/examples-gallery";
import { ExamplesMarquee } from "@/components/landing/examples-marquee";

/** Real cards generated by this studio (no mockups). */
const EXAMPLES: ExampleCard[] = [
  // Первая половина — верхняя лента, вторая — нижняя; старые и новые
  // примеры перемешаны, чтобы стили и категории чередовались в обеих.
  { src: "/examples/dress.jpg", title: "Платье", style: "Мягкий лайфстайл" },
  { src: "/examples/pan.png", title: "Сковорода", style: "Графитовый гранит" },
  { src: "/examples/backpack.png", title: "Детский рюкзак", style: "Весёлый яркий" },
  { src: "/examples/shirt.jpg", title: "Рубашка", style: "Чистый маркетплейс" },
  { src: "/examples/carvac.png", title: "Автопылесос", style: "Техно тёмный" },
  { src: "/examples/bedding.png", title: "Постельное бельё", style: "Нежный текстиль" },
  { src: "/examples/hoodie.jpg", title: "Худи", style: "Поп-арт" },
  { src: "/examples/thermomug.png", title: "Термокружка", style: "Чистый минимал" },
  { src: "/examples/turka.jpg", title: "Турка медная", style: "Сцена-история" },
  { src: "/examples/catfood.png", title: "Корм для кошек", style: "Доверие и состав" },
  { src: "/examples/sneakers.jpg", title: "Кроссовки", style: "Яркий акцент" },

  { src: "/examples/coat.jpg", title: "Пуховик", style: "Премиум тёмный" },
  { src: "/examples/constructor.png", title: "Конструктор", style: "Поп-комплект" },
  { src: "/examples/humidifier.jpg", title: "Увлажнитель", style: "Бирюзовый фреш" },
  { src: "/examples/belt.png", title: "Кожаный ремень", style: "Премиум кожа" },
  { src: "/examples/jeans.jpg", title: "Джинсы", style: "Солнечный промо" },
  { src: "/examples/organizer.png", title: "Органайзер", style: "Скандинавский порядок" },
  { src: "/examples/speaker.jpg", title: "Колонка", style: "Поп-арт · по референсу" },
  { src: "/examples/shampoo.png", title: "Мужской шампунь", style: "Свежий контраст" },
  { src: "/examples/yogamat.jpg", title: "Коврик для йоги", style: "Бирюзовый фреш" },
  { src: "/examples/suitcase.jpg", title: "Чемодан", style: "Солнечный промо" },
  { src: "/examples/cream.jpg", title: "Крем для лица", style: "Мягкий лайфстайл" },
];

const FEATURES = [
  {
    icon: Wand2,
    title: "Фото товара по описанию",
    text: "Премиальное фото с нужным фоном и светом — за минуту, без фотографа.",
  },
  {
    icon: ScanSearch,
    title: "Анализ карточки",
    text: "ИИ оценивает текущую карточку и находит, что мешает продажам.",
  },
  {
    icon: Lightbulb,
    title: "Идеи для улучшения",
    text: "5–10 идей карточек под вашу категорию и аудиторию.",
  },
  {
    icon: ImageIcon,
    title: "Из вашего снимка",
    text: "Загрузите своё фото — студия заменит фон и подачу, товар останется вашим.",
  },
  {
    icon: LayoutTemplate,
    title: "Инфографика под маркетплейс",
    text: "Готовая карточка с русским текстом: стили, композиции и плашки — внутри изображения.",
  },
  {
    icon: Download,
    title: "Экспорт под размер",
    text: "900×1200, 1200×1600, 3:4, 4:5 — PNG и JPG в один клик.",
  },
];

const STEPS = [
  { icon: Upload, title: "Загрузите товар", text: "Фото товара или текущую карточку с маркетплейса." },
  { icon: Lightbulb, title: "Получите идеи", text: "ИИ предложит смыслы и закроет боли клиента." },
  { icon: Wand2, title: "Сгенерируйте карточку", text: "Структурный промпт → дорогой визуал." },
  { icon: Download, title: "Скачайте результат", text: "Готовая графика в нужном размере." },
];

export default async function LandingPage() {
  // The landing is public; greet an already-authenticated visitor properly —
  // otherwise logging in "does nothing" visually (the page looks identical).
  const secret = process.env.AUTH_SECRET;
  const token = cookies().get(SESSION_COOKIE)?.value;
  const authed = secret ? Boolean(await verifySessionToken(secret, token)) : false;
  return (
    <div className="min-h-screen surface-gradient">
      {/* Nav */}
      <header className="container flex h-16 items-center justify-between gap-2">
        <Link href="/" className="flex min-w-0 items-center gap-2">
          <div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-gradient-to-br from-primary to-blue-500 text-white shadow-md">
            <Gem className="h-5 w-5" />
          </div>
          <span className="whitespace-nowrap text-sm font-semibold sm:text-base">
            Kartogen
          </span>
        </Link>
        <div className="flex shrink-0 items-center gap-1.5 sm:gap-3">
          {authed ? (
            <Button asChild variant="gradient" size="sm">
              <Link href="/dashboard">
                В студию
                <ArrowRight className="h-4 w-4" />
              </Link>
            </Button>
          ) : (
            <>
              <Button asChild variant="ghost" size="sm">
                <Link href="/login">Войти</Link>
              </Button>
              <Button asChild variant="gradient" size="sm">
                <Link href="/register">
                  <span className="sm:hidden">Начать</span>
                  <span className="hidden sm:inline">Начать бесплатно</span>
                </Link>
              </Button>
            </>
          )}
        </div>
      </header>

      {/* Hero */}
      <section className="container flex flex-col items-center pt-20 pb-16 text-center">
        <Badge variant="secondary" className="mb-5 gap-1.5">
          <Sparkles className="h-3.5 w-3.5 text-primary" />
          AI-студия контента для маркетплейсов
        </Badge>
        <h1 className="max-w-4xl text-4xl font-bold tracking-tight sm:text-5xl lg:text-6xl">
          Создавайте премиальные карточки для <span className="text-gradient">маркетплейсов</span> с
          помощью ИИ
        </h1>
        <p className="mt-5 max-w-2xl text-lg text-muted-foreground">
          Анализируйте товар, получайте идеи и генерируйте продающую инфографику за минуты.
        </p>
        <div className="mt-8 flex flex-col gap-3 sm:flex-row">
          <Button asChild size="lg" variant="gradient">
            <Link href={authed ? "/dashboard" : "/register"}>
              {authed ? "Открыть студию" : "Начать бесплатно"}
              <ArrowRight className="h-4 w-4" />
            </Link>
          </Button>
          <Button asChild size="lg" variant="outline">
            <Link href="#examples">Посмотреть примеры</Link>
          </Button>
        </div>
        {!authed && (
          <p className="mt-3 flex items-center gap-1.5 text-sm text-muted-foreground">
            <Dna className="h-4 w-4 text-primary" />
            20 генов в подарок при регистрации — хватит на первые карточки
          </p>
        )}

        {/* Hero preview strip — real generated cards */}
        <div className="mt-16 grid w-full max-w-5xl grid-cols-2 gap-4 sm:grid-cols-4">
          {EXAMPLES.slice(0, 4).map((c, i) => (
            <div
              key={c.src}
              className={`relative aspect-[3/4] overflow-hidden rounded-2xl shadow-lg ring-1 ring-black/5 ${
                i % 2 === 1 ? "sm:translate-y-6" : ""
              }`}
            >
              <Image
                src={c.src}
                alt={`${c.title} — ${c.style}`}
                fill
                priority={i < 2}
                sizes="(max-width: 640px) 50vw, 25vw"
                className="object-cover"
              />
            </div>
          ))}
        </div>
      </section>

      {/* Features */}
      <section className="container py-16">
        <h2 className="text-center text-3xl font-bold tracking-tight">Возможности</h2>
        <div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">
          {FEATURES.map((f) => (
            <div key={f.title} className="glass rounded-2xl p-6">
              <div className="flex h-11 w-11 items-center justify-center rounded-xl bg-primary/10 text-primary">
                <f.icon className="h-5 w-5" />
              </div>
              <h3 className="mt-4 font-semibold">{f.title}</h3>
              <p className="mt-1.5 text-sm text-muted-foreground">{f.text}</p>
            </div>
          ))}
        </div>
      </section>

      {/* How it works */}
      <section className="container py-16">
        <h2 className="text-center text-3xl font-bold tracking-tight">Как это работает</h2>
        <div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">
          {STEPS.map((s, i) => (
            <div key={s.title} className="relative rounded-2xl border bg-card p-6">
              <div className="absolute -top-3 left-6 flex h-7 w-7 items-center justify-center rounded-full bg-gradient-to-br from-primary to-blue-500 text-xs font-bold text-white">
                {i + 1}
              </div>
              <s.icon className="h-6 w-6 text-primary" />
              <h3 className="mt-3 font-semibold">{s.title}</h3>
              <p className="mt-1 text-sm text-muted-foreground">{s.text}</p>
            </div>
          ))}
        </div>
      </section>

      {/* Examples gallery — real output of the studio */}
      <section id="examples" className="container py-16">
        <h2 className="text-center text-3xl font-bold tracking-tight">Примеры карточек</h2>
        <p className="mt-2 text-center text-muted-foreground">
          Все карточки ниже сгенерированы этой студией — текст, композиция и стиль подбираются
          автоматически под каждый товар
        </p>
        <ExamplesMarquee items={EXAMPLES} />
      </section>

      {/* CTA */}
      <section className="container py-20">
        <div className="overflow-hidden rounded-3xl bg-gradient-to-br from-primary via-indigo-600 to-blue-600 p-10 text-center text-white sm:p-16">
          <h2 className="text-3xl font-bold tracking-tight sm:text-4xl">
            Готовы делать карточки, которые продают?
          </h2>
          <p className="mx-auto mt-3 max-w-xl text-white/85">
            Регистрация за минуту, 20 генов в подарок. Тексты, идеи и анализ фото — бесплатно,
            платите только за готовые изображения.
          </p>
          <Button asChild size="lg" variant="secondary" className="mt-8">
            <Link href={authed ? "/dashboard" : "/register"}>
              {authed ? "Открыть студию" : "Начать бесплатно"}
              <ArrowRight className="h-4 w-4" />
            </Link>
          </Button>
        </div>
      </section>

      <footer className="container flex flex-col items-center gap-3 border-t py-8 text-center text-sm text-muted-foreground">
        <p>Kartogen — AI-студия карточек для маркетплейсов</p>
        <nav className="flex flex-wrap justify-center gap-x-4 gap-y-1">
          <Link href="/pricing" className="hover:text-foreground">
            Тарифы
          </Link>
          <Link href="/terms" className="hover:text-foreground">
            Пользовательское соглашение
          </Link>
          <Link href="/offer" className="hover:text-foreground">
            Публичная оферта
          </Link>
          <Link href="/privacy" className="hover:text-foreground">
            Политика обработки персональных данных
          </Link>
          <a href="mailto:admin@kartogen.ru" className="hover:text-foreground">
            admin@kartogen.ru
          </a>
        </nav>
        <p className="text-xs">
          Сервис не аффилирован с Wildberries, Ozon и иными маркетплейсами.
        </p>
      </footer>
    </div>
  );
}
